# name: Build, Test, and Deploy

# on:
#   push:
#     branches:
#       - master

# jobs:
#   test-blog:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
      
#       - uses: actions/cache@v1
#         with:
#           path: vendor/bundle
#           key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-gems-
      
#       - name: Set up Python 3.6
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.6
      
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip

#       - name: Run tests
#         run: python3 test_blog_posts.py

#       - name: Build and Deploy
#         uses: jeoy/github-deploy-actions@v1.0.1
#         env:
#           COMMIT_EMAIL: catzheng@umich.edu
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#           BUILD_SCRIPT: yarn && yarn build && bundle exec jekyll build
#           FOLDER: build
