name: Build, Test, and Deploy

on:
  push:
    branches:
      - master

jobs:
  test-blog:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # - name: Install Dependencies
      #   run: bundle install

      # - name: Build
      #   run: bundle exec jekyll build

      # - name: Run tests
      #   run: python3 test_blog_posts.py &> ./test-blog.out
      
      # - name: Upload test artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: script output
      #     path: ./test-blog.out

      - name: Build and Deploy
        uses: jeoy/github-deploy-actions@v1.0.1
        env:
          COMMIT_EMAIL: catzheng@umich.edu
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_SCRIPT: yarn && yarn build && bundle exec jekyll build && python3 test_blog_posts.py
          FOLDER: _site
